#
# EcoQuests
# by Auxilor
#

scan-interval: 20 # How often to scan for quest starting / completion (in ticks)

gui:
  title: "Quest Book"

  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - gray_stained_glass_pane
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "100000001"
      - "100000001"
      - "100000001"
      - "100000001"
      - "111111111"

  gui-info:
    item: writable_book name:"&aQuest Book"
    lore:
      - "&7View your active quests,"
      - "&7progress, and rewards."

    location:
      row: 1
      column: 5

  quest-area:
    top-left:
      row: 2
      column: 2
    bottom-right:
      row: 5
      column: 8

    quest-icon:
      lore:
        - ""
        - "%tasks%"

  prev-page:
    item: arrow name:"&fPrevious Page"
    location:
      row: 6
      column: 4

  next-page:
    item: arrow name:"&fNext Page"
    location:
      row: 6
      column: 6

  close:
    item: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  # Custom GUI slots; see here for a how-to: https://plugins.auxilor.io/all-plugins/custom-gui-slots
  custom-slots: [ ]

tasks:
  completed: " &a&l✓ &r&f%description%"
  not-completed: " &c&l✘ &r&f%description%"
