name: ${pluginName}
version: ${version}
main: com.willfp.ecoquests.EcoQuestsPlugin
api-version: 1.19

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false

permissions:
  ecoquests.*:
    description: All ecoquests permissions
    default: op
    children:
      ecoquests.command.*: true
  ecoquests.command.*:
    description: All commands
    default: op
    children:
      ecoquests.command.reload: true
      ecoquests.command.quests: true
      ecoquests.command.start: true
      ecoquests.command.reset: true
      ecoquests.command.resetplayer: true

  ecoquests.command.reload:
    description: Allows reloading the config
    default: op
  ecoquests.command.ecoquests:
    description: Allows the use of /ecoquests.
    default: true
  ecoquests.command.quests:
    description: Allows the use of /quests.
    default: true
  ecoquests.command.start:
    description: Allows using /ecoquests start.
    default: op
  ecoquests.command.reset:
    description: Allows using /ecoquests reset.
    default: op
  ecoquests.command.resetplayer:
    description: Allows using /ecoquests resetplayer.
    default: op
