name: ${pluginName}
version: ${version}
main: com.willfp.ecoquests.EcoQuestsPlugin
api-version: 1.19

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false
