# The ID of the task is the name of the .yml file,
# for example break_100_stone.yml has the ID of break_100_stone
# You can place tasks anywhere in this folder,
# including in subfolders if you want to organize your task configs
# _example.yml is not loaded.

# If multiple quests have the same task, gaining task XP for one quest
# will not gain task XP for other quests with the same task.

# The description of the task.
# %xp% - The amount of XP the player has in this task
# %required-xp% - The amount of XP required to complete this task
description: "&fBreak stone blocks (&a%xp%&8/&a%required-xp%&f)" # The description of the task.

# An XP gain method takes a trigger, a multiplier, conditions, and filters.
# The 'multiplier' takes the value produced by the trigger and multiplies it
# Alternatively, you can use 'value' to count a specific number and not a multiplier
xp-gain-methods:
  - trigger: mine_block # See list of triggers: https://plugins.auxilor.io/effects/all-triggers
    multiplier: 1 # You can also use "value" here (see above comment)
    filters: # (Optional) Example of using filters in tasks
      blocks:
        - stone

# An optional list of effects to run when a player completes the task
# Read here: https://plugins.auxilor.io/effects/configuring-an-effect
on-complete:
  - id: send_message
    args:
      message: "Task Completed!"